workflows:
  iOS_build:
    environment:
      flutter: stable

    scripts:
      - flutter clean
      - flutter pub get
      - open ios/Runner.xcworkspace
      - xcodebuild -workspace ios/Runner.xcworkspace -scheme Runner -sdk iphoneos -configuration Release build CODE_SIGNING_ALLOWED=NO
      - flutter build ios

    artifacts:
      - build/ios/*.ipa

    publishing:
      email:
        recipients:
          - chethiyabandaraherath@email.com