workflows:
  iOS_build:
    environment:
      flutter: stable

    scripts:
    - flutter pub get
    - cd ios
    - pod install
    - cd ..
    - flutter build ios --release --no-codesign

  artifacts:
    - build/ios/*.ipa

    publishing:
      email:
        recipients:
          - chethiyabandaraherath@email.com