# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Runner' do
  use_frameworks!
  # Add your pods here
  pod 'path_provider_foundation', '~> 2.3.1'
end